### PR TITLE
Harter edit

### PR DESCRIPTION
**Pull request by harterj**
A few minor changes I hope won't break anything...

### CODE REVIEW

**Comment by albeanth** [comment]
so much for the review process eh? 😛

**Comment by harterj** [comment]
well, #duh ;) we only review if it breaks something... are you coming back soon?

**Comment by albeanth** [comment]
in my office now!

**Comment by harterj** [comment]
nice, I'll come say hey later. At home, got dentist appointment in a bit (cracked my damn tooth in NM...) and meeting TP after. I have an official desk now! We need you to move in there...

**Comment by albeanth** [comment]
once Trevor defends and moves out I may move in there. depends on the AC situation in that office. I've heard it gets hot in there....

**Pull request merged**
