### PR TITLE
update extra projects

### PR DESCRIPTION
**Pull request by dougwoods3**
Also the Gemfile.lock got modified somehow. It looks like different versions of something. Maybe good, maybe bad?

### CODE REVIEW

**Comment by albeanth** [comment]
Did you fire up Jekyl to preview your changes?

**Comment by harterj** [comment]
You probably got a newer version of Ruby when you did the wipe and reinstall. I think the lock update is probably okay, but it would be smart to run it locally and check before it gets pushed up

**Comment by albeanth** [comment]
Or you could submit a new PR without the gemfile.lock change request

**Comment by dougwoods3** [comment]
Yeah, the site works locally. Do you guys want to test it locally?

**Comment by harterj** [comment]
If it works for you it should be fine on the server. :shipit:

**Pull request merged**
