### PR TITLE
Pushing personal page update v1

### PR DESCRIPTION
**Pull request by nickwhitman1993**
This is my personal page update, first version. Please let me know if there is anything wrong.

### CODE REVIEW

**Comment by harterj** [comment]
Notifying @albeanth and @dougwoods3 on this one as well. @nickwhitman1993, you can tag people by using the .@ symbol, that way we see the notification. Also, you can add reviewers and assignees to the issue by using the bar on the right. Just click and drag.

**Review by harterj — COMMENTED** [review]
I think it would be good to think about resizing these pictures, because they are gonna be huge and probably make your flow look kinda screwy. Not so much the headshot, but FREC1, I'd recommend shrinking its dimension by 0.5

**Comment by harterj** [comment]
For instance, if you resize the pic on your computer, you can use
``
and not need to include the dimensions on it.

**Comment by harterj** [comment]
:shipit:

**Comment by harterj** [comment]
I merged it, so you'll get an idea of how it actually looks. Now you can play with making a new branch and working with that one, too!

**Comment by albeanth** [comment]
@nickwhitman1993 you can also tag myself, doug, and jackson with the tag, @rtrp/admins 

just to save a little bit of typing.

**Comment by harterj** [comment]
:thumbsup:

**Pull request merged**
