### PR TITLE
Rename ParticleSystem.md to index.md

### PR DESCRIPTION
**Pull request by dougwoods3**

### CODE REVIEW

**Comment by albeanth** [comment]
just so you know @dougwoods3 you are getting 404's on the links for the particle system project link on your personal page.

**Comment by albeanth** [comment]
might I suggest jekyll in your future my friend?

**Comment by dougwoods3** [comment]
@albeanth I got jekyll set up locally but the links from the main page all link to the actual internet. How do I check out the links locally?

**Comment by albeanth** [comment]
@harterj can probably answer this better than I but I can try. direct from the gitter chat from jackson:

"The command to start the server to allow localhost access :: **bundle exec jekyll serve --config _modConfig.yml**"

This will start to run the "server". Don't ctrl-c it, let it run. Then, there should be a localhost address that the terminal will spit out once you do the jekyll serve command. Copy that and paste it into your web browser. You will be able to observe changes on the fly as long you leave the server running. Just be sure to save the edits you make in atom and then reload the localhost page in the browser.

**Comment by dougwoods3** [comment]
@albeanth @harterj thanks guys, a quick first glance shows that it is working. I needed the `--config _modConfig.yml` bit.

**Pull request merged**
