### PR TITLE
Revamped Proflie

### PR DESCRIPTION
**Pull request by Yoshimitsu45**
Added basic descriptions of research and personal interests,

### CODE REVIEW

**Comment by Yoshimitsu45** [comment]
I hope this works to designate an assignee:  @harterj @dougwoods3 @albeanth

**Comment by dougwoods3** [comment]
It worked. You can also tag all three of us @rtrp/admins.

:shipit:

**Comment by Yoshimitsu45** [comment]
B.A. Thanks brah!

**Comment by dougwoods3** [comment]
A styling note: you've figured out that a new line in the code doesn't make a new line on your page (same as latex). You can force a new line in markdown by putting a double <space > at the end of any particular line. Or if you press double <enter > you create a new paragraph.

**Pull request merged**
