### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by pharnb**

### CODE REVIEW

**Comment by albeanth** [comment]
@rtrp/admins  🚢

**Comment by pharnb** [comment]
@rtrp/admins Jackson Keppen isn't yet a user but he needs to make a bio

**Comment by pharnb** [comment]
He's here with me in the library now

**Comment by dougwoods3** [comment]
You're right. We're missing Jackson Keppen.

@pharnb see if you can copy the sytanx to add a link for him on our homepage. It's the index.md file on in the home directory.

**Comment by albeanth** [comment]
@dougwoods3  he has. that's what this merge request is for hah

@pharnb have Jackson make an account and get in the group. once he is in we will merge it in.

**Comment by pharnb** [comment]
He's got an account, keppenj.  I don't remember how to have him join the group though.  I can figure it out though.

**Comment by albeanth** [comment]
@pharnb there are directions for that on the wiki.

Go to the rtrp/osu-transport page and then over to the "wiki" tab. It'll walk you through up to that part.

**Comment by albeanth** [comment]
@pharnb I see he's in the group now so I'm going to merge this through.

**Pull request merged**
