### PR TITLE
update resume

### PR DESCRIPTION
**Pull request by dougwoods3**

### CODE REVIEW

**Comment by albeanth** [comment]
🚢  it

**Comment by albeanth** [comment]
there isn't the mystical commit updating your branch! woo! 😝

**Comment by dougwoods3** [comment]
This one was straight out of compton. err, my terminal.

Thank you,
Doug Woods

https://rtrp.github.io/osu-transport/users/woodsdou/

**Comment by albeanth** [comment]
https://www.youtube.com/watch?v=-JfEJq56IwI

**Pull request merged**
