### PR TITLE
adding link to resume and updated conferences

### PR DESCRIPTION
**Pull request by harterj**
Seeing if this works...I think it will. @rtrp/admins

### CODE REVIEW

**Comment by albeanth** [comment]
@harterj did you try and test it in jekyl?

**Comment by harterj** [comment]
I don't remember how 😢

**Comment by albeanth** [comment]
that makes two of us! haha

I know the command to start jekyl is on the wiki

but actually getting it to work is a different story

**Comment by harterj** [comment]
throwing caution to the wind :shipit:

**Comment by harterj** [comment]
score, it works. I just need to fix the formatting so it shows up on a newline

**Comment by dougwoods3** [comment]
nicely done.

**Comment by albeanth** [comment]
👍

**Pull request merged**
