### PR TITLE
Updating Doug's page, In Memoriam

### PR DESCRIPTION
**Pull request by nickwhitman1993**
@rtrp/admins Pending approval, we can push this update though.

### CODE REVIEW

**Comment by ryanstwrt** [comment]
@nickwhitman1993 I'm still not seeing the figures on Doug's page. Did you push the pictures?

**Comment by nickwhitman1993** [comment]
@ryanstwrt Yeah I did, I am wondering if it might take a minute to push the pictures since they are large. I was having that issue as well. If you go look at them, they are definitely there though.

**Comment by ryanstwrt** [comment]
They are definitely there, and the path to them looks correct. I'll check back again in 15 and see.

**Comment by nickwhitman1993** [comment]
@ryanstwrt I figured out why. The path to the files is rtrp.github.io/ etc. The pictures haven't been pushed to that path yet. Once this pull request is merged, it should work.

**Comment by ryanstwrt** [comment]
Sounds good. I'll got ahead and merge it then.

**Comment by aaronjamesreynolds** [comment]
@rtrp/admins It looks like a number of the pictures are still not rendering. Also, were we going to wait until we got the okay from Dr. Palmer to put this up?

**Comment by ryanstwrt** [comment]
Ahh.. I believe you are correct on waiting, perhaps I was a bit hasty on the merge...

It looks like the Drinks2 picture should be .JPG not .jpg
Along with that Dressy should be .jpeg not .jpg

We can revert to this pull if we want?

**Comment by aaronjamesreynolds** [comment]
That sounds good to me 👍

**Comment by nickwhitman1993** [comment]
@ryanstwrt Good catch. I tried that but I guess forgot to push those changes through. And yes, I was waiting 'til further approval from the parties that this thing might be sensitive too, but also, I am thinking that maybe we should just do it and then show it and ask for approval. Maybe I too often use the mentality "do first and act for forgiveness later".. 😨

**Comment by nickwhitman1993** [comment]
@albeanth

**Pull request merged**
