### PR TITLE
changes to profile: resume change, updated journal reference

### PR DESCRIPTION
**Pull request by harterj**
Added some stuff...had to fix my resume and then update a citation...

### CODE REVIEW

**Comment by albeanth** [comment]
🚢 it

**Comment by dougwoods3** [comment]
Your resume is missing closing ] on your journals.

**Comment by harterj** [comment]
@dougwoods3 did that fix it?

**Comment by dougwoods3** [comment]
nope...

**Comment by albeanth** [comment]
☝️ this reply is so Palmeresque it hurts haha

**Comment by harterj** [comment]
:shipit: ?

**Comment by harterj** [comment]
@rtrp/admins you know he can read these comments..if he ever figures out how to get on Github ;]

**Comment by albeanth** [comment]
Well, if he ever does see it then we can all have a laugh! 😄

**Pull request merged**
