### PR TITLE
BCL-edits

### PR DESCRIPTION
**Pull request by lilleybe**
Not sure if my research jpg will show up. Any ideas?

### CODE REVIEW

**Comment by nickwhitman1993** [comment]
@rtrp/admins What is the status on this PR?

**Comment by aaronjamesreynolds** [comment]
Uhhh, honestly I don't know what's going on here. The changes in @lilleybe's page are already on the website, as far as I can tell. 

@lilleybe, do you remember what you were trying to do here? Sorry this got so long in the tooth...

**Comment by nickwhitman1993** [comment]
@rtrp/admins If there aren't any changes that are needed, we can close this PR out without merging (is that the best way to do it?) @lilleybe can you comment?

**Comment by aaronjamesreynolds** [comment]
Ben has indicated that his changes have already been incorporated, and that this merge is unnecessary.

> "...my page as it stands looks fine. I think that was for an older version."

I'll close this out.

**Pull request closed without merging**
