### PR TITLE
Merge pull request #10 from rtrp/gh-pages

### PR DESCRIPTION
**Pull request by dougwoods3**
update my fork

### CODE REVIEW

**Comment by harterj** [comment]
@rtrp/admins I'm confused. How does updating your personal fork affect the master, and why would you need to merge it in? Isn't gh-pages the upstream, and wouldn't updating your fork just change the origin? (ie your own copy)

**Comment by dougwoods3** [comment]
I'm glad you noticed this. It was strange to me too. Order of events:
1) updated my index.md on my fork.
2) merge upstream into my fork.
3) PR my fork to upstream. This showed that no files were changed even though they were in step 1.
4) merge my fork to upstream

I just pushed forward (step 4) to see what would happen.

**Comment by harterj** [comment]
So, what were you trying to do? Update index, from where? (explicitly)

**Comment by harterj** [comment]
Sorry, let me ask a different one: So, you want to update index, and you need to update your local fork with what was done on the upstream. Did you pull before you started to edit? Did you fetch upstream, then rebase to upstream/gh-pages? That's how I tend to do it and don't see this type of issue @albeanth

**Comment by dougwoods3** [comment]
I updated my users/woodsdou/index.md and events/index.md.

I did it from the web browser on my fork.

**Comment by albeanth** [comment]
@dougwoods3 this PR references another PR from over a year ago... were you trying to pull something back from the past? 

also, what changes were you trying to do? The PR you submitted shows no changes. Jackson and I are confused as to what you did

**Comment by dougwoods3** [comment]
I made commit
https://github.com/dougwoods3/osu-transport/commit/1ec504c627cf6dd9462cdc6da975e14e15b18ac0#diff-96c2a4ae9ed15a3a29893b9024cedc08

and then I merged the upstream into my origin
https://github.com/dougwoods3/osu-transport/commit/390db6224d2e9e3cf04cd2fac0b4c90eef77c6b7#diff-96c2a4ae9ed15a3a29893b9024cedc08

**Comment by harterj** [comment]
The changes are only shown in his personal fork @rtrp/admins

**Comment by albeanth** [comment]
@dougwoods3 I see the changes you made on your fork - so I see what you were trying to do. But something odd happened in the PR and things got screwy. Also, I know it was a very minor change to be made but what happened to the review process before any merges?

In an effort to keep things clean and not introduce some potentially odd bugs/recursiveness to past PRs/commits @dougwoods3 what do you think about reverting this PR and submitting a new one?

**Comment by dougwoods3** [comment]
Word. I'll try to fix it.

I noticed that no files were changed during my PR so I just wanted to see what would happen when I merged it.

**Comment by harterj** [comment]
@rtrp/admins I would agree with Tony on this. It seems harmless right now, but it could introduce some odd subtle bug we don't see until much later

@dougwoods3 I don't think this would have happened if you didn't have admin status, so I guess I'd just mention that. Obviously not critical since it's just a website, but for the future, etc.

**Comment by albeanth** [comment]
@rtrp/admins what's even weirder is that if you look on the live website, the changes that Doug made are there. But there's no record of them in the PR they were supposed to come along with. 

Very strange Github, very strange.

**Pull request merged**
