### PR TITLE
Changing link to point to my dept page

### PR DESCRIPTION
**Pull request by albeanth**
- until I update my rtrp page (or if I decide to), I'll just have this point to my new dept webpage

### CODE REVIEW

**Review by nickwhitman1993 — APPROVED** [review]
Looks good. :shipit:

**Review by aaronjamesreynolds — APPROVED** [review]
Fancy department page! Nice. Looks good to me.

**Comment by nickwhitman1993** [comment]
@albeanth do you want your other link to point to the dept page too?

**Comment by albeanth** [comment]
@nickwhitman1993 sure. ~But what other link?~ 
Edit: I just realized the mistake I made. If you revert and reopen this PR, I'll fix it. 

Also. Off topic here, but feel free to remove @harterj and I from the admin/moderator list.

**Comment by nickwhitman1993** [comment]
@albeanth should be reverted. Reopening this PR.

**Comment by nickwhitman1993** [comment]
@albeanth trying to figure out how to re-open this...

**Comment by albeanth** [comment]
@nickwhitman1993 reopening may only be for issues. My mistake. I'll just submit a new PR.

**Pull request merged**
