### PR TITLE
Add some common derivations to the Wiki page and update my personal page

### PR DESCRIPTION
**Pull request by aaronjamesreynolds**
I've got all these .tex files with some handy derivations that I thought would make a nice addition to the Wiki page. Let me know if you disagree, or see any goofs. I have been known to goof.

### CODE REVIEW

**Comment by aaronjamesreynolds** [comment]
You can check out the changes to the Wiki here: 

https://aaronjamesreynolds.github.io/osu-transport/wiki/

**Comment by aaronjamesreynolds** [comment]
You can check out the changes to my personal page here:

https://aaronjamesreynolds.github.io/osu-transport/users/reynolaa/

**Comment by aaronjamesreynolds** [comment]
Also, if you want to be able to see your images on your personal fork, you can link with a relative path instead of using the {{ site.url }} approach. Makes troubleshooting and fine tuning image placement a lot easier.

**Comment by ryanstwrt** [comment]
Ooh your looking fancy with your moving pictures! :)
I don't see any immediate problems with your page or the updated derivations.
@nickwhitman1993 anything you notice?

**Comment by aaronjamesreynolds** [comment]
@nickwhitman1993, mind taking a look?

**Comment by nickwhitman1993** [comment]
@aaronjamesreynolds looks ok to me. :shipit:

**Pull request merged**
