### PR TITLE
albeanth - updating personal page

### PR DESCRIPTION
**Pull request by albeanth**
and removing Lara from /users (sorry Lara!)

### CODE REVIEW

**Comment by dougwoods3** [comment]
Ask Lara if she would want a page on here. She might want a quick version in the past students.

**Comment by albeanth** [comment]
@dougwoods3 we can ask her and see if she wants to be our first "past student" :P

**Comment by dougwoods3** [comment]
@albeanth word. I cc'd you in an email.

**Comment by albeanth** [comment]
@dougwoods3 just saw it 👍  also - I have updates on the gitter chat

**Pull request merged**
