### PR TITLE
dummy change to learn about merge request from a fork

### PR DESCRIPTION
**Pull request by harterj**
Title says it all. Added "R." to my name string. Will not cause any changes whatsoever.

### CODE REVIEW

**Comment by dougwoods3** [comment]
@albeanth @harterj I was wondering about this myself. It could be a good way for the others to make edits and merge back to the rtrp/. Keep us in the loop about this one.

I'm also curious what barriers other might run into since they aren't admin.  It could also help us write the wiki instructions. Do either of you guys have a second GitHub account?

**Comment by harterj** [comment]
@albeanth  @dougwoods3  Palmer will be trying this out either tonight or tomorrow. Almost done with an email to him, I'll CC you guys

**Comment by albeanth** [comment]
@harterj remember I was doing all my edits last night from a fork? I think tonight I'm going to try and get something written up in the github wiki on what to expect from going that route. Not much is different with the exception that once your merge request is accepted, your fork is behind rtrp/. I just need to figure out the most streamlined way to go about that part.

**Comment by dougwoods3** [comment]
@harterj You mean he'll try making a page?

**Comment by harterj** [comment]
its pretty easy with the right commands to sync your fork with gh-pages head. but I agree, everyone will be required (apart from us, perhaps) to do work with a fork.

**Comment by albeanth** [comment]
@harterj yeah, I feel like I've done it before. Idk why it wouldn't go last night.

**Comment by harterj** [comment]
Sent the email, you should have it. Merging this in now...

**Pull request merged**
