### PR TITLE
Removing Gemfile files to address security issues.

### PR DESCRIPTION
**Pull request by aaronjamesreynolds**
A great number of Jekyll dependencies of varying versions are present in the Gemfile files, specifically Gemfile.lock. Jekyll has known security vulnerabilities and these versions must be updated to the current release. Doing so has the potential of turning the RTRP page into a potato. In the interest of keeping things simple and expedient, we've decided to remove these files and the functionality they enable. Should this functionality be desired in the future, we'll return to the issue. ( Fixes issue #182 )

### CODE REVIEW

**Comment by albeanth** [comment]
I'm all on board with taking Jekyll features out. 🚢 it.

> Jekyll has known security vulnerabilities and these versions must be updated to the current release. Doing so has the potential of turning the RTRP page into a potato.

Can you elaborate on how this will turn the page into a potato? Are there other options we could use other than Jekyll?

**Comment by aaronjamesreynolds** [comment]
I suspect that updating packages that rely on Jekyll 0.X.X to Jekyll 3.X.X may cause some issues such as, in the worst case, making portions of the page inoperable (or turning them into potatoes, as I hear the youth say). Now, I have no intimate knowledge of how Jekyll works, so maybe not. 

There may be other options to substitute the functionality of Jekyll. I haven't looked into it.

**Comment by albeanth** [comment]
Got it. Let's go ahead and get rid of it. In the future we can revisit it
or look into alternatives.

**Comment by nickwhitman1993** [comment]
Roger. :shipit: I approve

**Pull request merged**
