### PR TITLE
Fixed Security Issues in Gemfile.lock

### PR DESCRIPTION
**Pull request by nickwhitman1993**
@rtrp/admins 

I believe I fixed the security issues with rack and loofah in the Gemfile.lock.

🐐

### CODE REVIEW

**Comment by albeanth** [comment]
These changes look fine to me. Just need to address the commonalities between this PR and PR #180.

@dougwoods3 hope you're ok with Nick taking the initiative and moving you into an alumni section!

**Comment by nickwhitman1993** [comment]
Sorry @dougwoods3 👴

**Comment by dougwoods3** [comment]
Well, I had to admit growing up eventually...


Thank you,
Doug Woods

**Comment by aaronjamesreynolds** [comment]
... :shipit: 
Did I do it right?

**Comment by albeanth** [comment]
@aaronjamesreynolds like a pro! 👍

**Comment by aaronjamesreynolds** [comment]
Well, now we've got more alerts than we started with. Hmm.

**Comment by albeanth** [comment]
~~Can always reopen this PR and address them.~~

If you do that ⬆️ you won't see the new issues. This will likely need to be a new PR.

**Pull request merged**
