### PR TITLE
Add guide for creating an RTRP page. 

### PR DESCRIPTION
**Pull request by aaronjamesreynolds**
Thought I'd write up the process for creating an RTRP page, so we don't have to muddle through it each time. Let me know if you see any issues! You can find the process in compiled markdown here: 

[aaron's fork](https://aaronjamesreynolds.github.io/osu-transport/wiki/start_my_page)

### CODE REVIEW

**Comment by aaronjamesreynolds** [comment]
Hey my dudes, @ryanstwrt @nickwhitman1993, any thoughts on this wiki page?

**Comment by ryanstwrt** [comment]
It looks good to me, @nickwhitman1993 any comments? If not, I'll go ahead and merge it.

**Comment by aaronjamesreynolds** [comment]
I think we can go ahead and merge it.

**Comment by aaronjamesreynolds** [comment]
Alrighty I'm just gonna merge it.

**Pull request merged**
