### PR TITLE
Revert "Merge pull request #10 from rtrp/gh-pages"

### PR DESCRIPTION
**Pull request by dougwoods3**
Reverts rtrp/osu-transport#147

### CODE REVIEW

**Comment by albeanth** [comment]
🚢  it dude bro

**Comment by albeanth** [comment]
@dougwoods3 if I were you, I would get my fork up to date with the changes that have happened

https://help.github.com/articles/syncing-a-fork/

Then get your changes up to speed on your fork and make a new PR for those changes.

**Comment by dougwoods3** [comment]
@rtrp/admins the changes I made are still there, despite the revert...

**Comment by albeanth** [comment]
something real weird happened. The original, potentially problematic merge, #147, had no changed files. So when you reverted _that_ merge nothing really happened. 

So if we look at the commit history for the ./Events section in the upstream rtrp repo, two commits from today (seem to be not associated with a pull request) are there. The same can be said for ./users/woodsdou/index.md

So, here's what I think what may have happened - @dougwoods3 you thought you were committing directly to your fork but rather you were committing directly to the rtrp page (since you did it online). 

That being said, if I'm right, we shouldn't have any recursive issues with the repo. Those were undone with the revert of #147. Doug just made a mistake and committed directly to the upstream rtrp repo (rather than to his fork and then making a reviewable PR).

**Pull request merged**
