### PR TITLE
add JDRF photo to Events

### PR DESCRIPTION
**Pull request by dougwoods3**

### CODE REVIEW

**Comment by albeanth** [comment]
Do you/we not have a picture that is straight on? Instead of at an angle?

**Comment by dougwoods3** [comment]
This was the only photo that @harterj  emailed out to us.

**Comment by albeanth** [comment]
I remember there were a few people taking pictures and that Jackson's brother was off to the side. Who was in the center? @harterj was it your mom in the center?

**Comment by albeanth** [comment]
@harterj @dougwoods3  you guys won the ans election dealeo?

**Comment by harterj** [comment]
@albeanth is there a fix for the logo yet? It's not showing up on my laptop..mobile either.

And yes, we won the election. I probably won't update for a while until @dougwoods3 and I have a chance to formulate our game plan.

**Comment by albeanth** [comment]
@harterj the logo issue is fixed. I forgot to update the pathing for the RTRP picture when I rearranged the logo directories... 

Well shoot, congrats dudes!

**Pull request merged**
