### PR TITLE
Update page + resume

### PR DESCRIPTION
**Pull request by harterj**
Update to my page to add a publication, resume fix, etc...

### CODE REVIEW

**Comment by albeanth** [comment]
This still exists! Who knew... lol

**Comment by harterj** [comment]
lol, I know. I am compelled to keep it current...

**Comment by harterj** [comment]
Hopefully it'll be moved to Senor Doug's section here in a couple months...

**Comment by harterj** [comment]
Merging, since you ain't doing your job :shipit:

**Comment by albeanth** [comment]
I think this is the job for @rtrp/admins which is essentially @aaronjamesreynolds these days.

**Comment by harterj** [comment]
Oh! Yeah I keep forgetting it's not us anymore...but rather @aaronjamesreynolds

Ok, back to your DFEMs!

**Comment by nickwhitman1993** [comment]
I see how it is @albeanth.

**Comment by albeanth** [comment]
lol I completely forgot you were an admin now @nickwhitman1993 !

You all should crack the whip on this website!

**Comment by nickwhitman1993** [comment]
As soon as the new term starts, I will definitely urge people (including myself) to update their pages. Consider it done! 

😀

**Pull request merged**
